services:
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile.postgres
    image: vaultify-db
    container_name: vaultify_db
    ports:
      - "5432:5432"
    volumes:
      - vaultify_pgdata:/var/lib/postgresql/data
      - ./vault_data:/app/vault_data
    environment:
      POSTGRES_DB: vaultify_db
      POSTGRES_USER: vaultify_user
      POSTGRES_PASSWORD: secret123

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: vaultify-app
    container_name: vaultify_app
    depends_on:
      - db
    stdin_open: true          # REQUIRED for interactive CLI
    tty: true                 # REQUIRED for prompt display
    command: ["/bin/sh", "-c", "java -jar /app/app.jar"]   # <--- THE FIX
    volumes:
      - ./vault_data:/app/vault_data

volumes:
  vaultify_pgdata:
